### ISSUE TITLE
Command "maintenance:release-lock" is not defined.

### ISSUE THREAD

**Issue by kaurov** [samynw/pimcore-maintenance-toolbox#6]
What can be a reason of following error mesage?

```
❯ php bin/console maintenance:release-lock versioncleanup

  Command "maintenance:release-lock" is not defined.

  Did you mean one of these?
      maintenance
      maintenance:list

```

I see you successfully registered command ReleaseLockCommand :
```
    # auto-register all commands as services
    Samynw\MaintenanceToolboxBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']
```

But still it causes the error althougth :list command works fine:
`php bin/console maintenance:list`

Versions:
    php8
    "pimcore/data-hub": "^1.2",
    "pimcore/pimcore": "^10.0",
    "samynw/pimcore-maintenance-toolbox": "^2.0"

**Comment by samynw** [comment]
Hi @kaurov !

The `release-lock` is not enabled by default, as releasing locks might result into unexpected behaviour (such as 2 jobs running parallel). You can enable the command in the extension manager through the Pimcore user interface.

See [Configuration](https://github.com/samynw/pimcore-maintenance-toolbox#configuration)

Look for the "edit" icon next to the bundle:
![Selection_999(842)](https://user-images.githubusercontent.com/11783803/180838254-e8f41be9-1d6f-4691-b377-2201464f0b5a.png)


Does this resolve your issue?
